spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: hugebigdream@gmail.com
    password: cbosmbztzvvbluez
    properties:
      mail:
        smtp:
          starttls:
            enable: true


  level:
    root: info
  mvc:
    static-path-pattern: /resources/**
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
